# tasks file
---
- name: install
  ansible.builtin.apt:
    name: "{{ pflogsumm_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - pflogsumm
    - pflogsumm-install

- name: update existing logrotate.d script
  ansible.builtin.lineinfile:
    dest: /etc/logrotate.d/rsyslog
    regexp: "^{{ item }}$"
    state: absent
  with_items: "{{ pflogsumm_logrotate_logfiles }}"
  tags:
    - configuration
    - pflogsumm
    - pflogsumm-configuration

- name: create custom logrotate.d script
  ansible.builtin.template:
    src: etc/logrotate.d/mail.j2
    dest: /etc/logrotate.d/mail
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - pflogsumm
    - pflogsumm-configuration

- name: create report script
  ansible.builtin.template:
    src: usr/local/sbin/pflogsumm-report.j2
    dest: /usr/local/sbin/pflogsumm-report
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - pflogsumm
    - pflogsumm-configuration
